services:
  ecomm-backend-srv:
    image: xamma/ecomm-backend:latest
    ports:
      - 8000:8000
  ecomm-frontend-srv:
    image: xamma/ecomm-frontend:latest
    ports:
      - 80:80
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
     - mongo_data:/data/db
volumes:
  mongo_data: